### ISSUE TITLE
Develop style guide for the guidebook

### ISSUE THREAD

**Issue by kristiholmes** [data2health/reusable-data-best-practices#2]

**Comment by kristiholmes** [comment]
Hi @jmcmurry and @RoseRelevo - handing off this issue to you both now, given workflow for the chapters.  @rchampieux and I haven't done more than discuss this topic, so there isn't any work ongoing on this item. Thanks!

**Comment by jmcmurry** [comment]
Given that ReadTheDocs doesn't give much wiggle room in terms of formatting, we probably don't need to worry too much about this. I did make a note about references being hyperlinked rather than just listed at the end. Aside from this I think most of our formatting concerns can be addressed by the structure. Going to provisionally close this. We can reopen if it proves necessary.
